### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by kkar** [maddisondesigns/Simple-Catalog-for-WooCommerce#1]
Fatal error: Can't use method return value in write context in /home/feral/public_html/newsite/wp-content/plugins/Simple-Catalog-for-WooCommerce-master/simple-catalog-for-woocommerce.php on line 296

**Comment by maddisondesigns** [comment]
What version of PHP are you using? If you’re using less than v5.5 I would recommend updating to at least 5.5

**Comment by maddisondesigns** [comment]
I'm going to assume updating to a later version of PHP fixed this issue so I'll close this now.
